---

# Main tasks file for ferm role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::ferm'
    - 'role::ferm::config'
    - 'role::ferm::init'
    - 'role::ferm::install'


- name: 'INSTALL | Manage OS family specific installation tasks'
  become: True
  include: "{{ role_path }}/tasks/install_{{ ansible_os_family | lower }}.yml"
  tags:
    - 'role::ferm'
    - 'role::ferm::install'


- name: 'SERVICE | Manage service'
  become: True
  service:
    name: "{{ ferm_service_name }}"
    enabled: "{{ ferm_service_enabled }}"
  tags:
    - 'role::ferm'
    - 'role::ferm::config'
    - 'role::ferm::install'


- name: 'CONFIG | Manage configuration'
  become: True
  include: "{{ role_path }}/tasks/configure.yml"
  tags:
    - 'role::ferm'
    - 'role::ferm::config'
